### PR TITLE
config: No more '#' or ';' comments; use '//' instead

### PR DESCRIPTION
**Pull request by dgw**
Any alternative idea that would let us keep using `#` for comments is welcome, but as described in the relevant commit message I don't think that's possible without some very dirty monkey-patching.

'Documentation' label because I'll have to make _damn sure_ I include very prominent notes about this in the changelog and migration guide. If someone loads an old config with now-unrecognized comments, Sopel will explode with a very unhelpful traceback:

```
$ sopel
Traceback (most recent call last):
  File "/mnt/c/Users/dgw/github/sopel/sopel/config/types.py", line 55, in __init__
    getattr(self, value)
  File "/mnt/c/Users/dgw/github/sopel/sopel/config/types.py", line 384, in __get__
    this_section = getattr(main_config, instance._section_name)
  File "/mnt/c/Users/dgw/github/sopel/sopel/config/__init__.py", line 218, in __getattr__
    section = self.ConfigSection(name, items, self)  # Return a section
  File "/mnt/c/Users/dgw/github/sopel/sopel/config/__init__.py", line 187, in __init__
    value = item[1].strip()
AttributeError: 'NoneType' object has no attribute 'strip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sopel", line 11, in <module>
    load_entry_point('sopel', 'console_scripts', 'sopel')()
  File "/mnt/c/Users/dgw/github/sopel/sopel/cli/run.py", line 680, in main
    return command(opts)
  File "/mnt/c/Users/dgw/github/sopel/sopel/cli/run.py", line 573, in command_legacy
    config_module = get_configuration(opts)
  File "/mnt/c/Users/dgw/github/sopel/sopel/cli/run.py", line 329, in get_configuration
    settings = utils.load_settings(options)
  File "/mnt/c/Users/dgw/github/sopel/sopel/cli/utils.py", line 338, in load_settings
    return config.Config(filename)
  File "/mnt/c/Users/dgw/github/sopel/sopel/config/__init__.py", line 119, in __init__
    validate=validate)
  File "/mnt/c/Users/dgw/github/sopel/sopel/config/__init__.py", line 173, in define_section
    setattr(self, name, cls_(self, name, validate=validate))
  File "/mnt/c/Users/dgw/github/sopel/sopel/config/types.py", line 65, in __init__
    value)
ValueError: Missing required value for core.ca_certs
```

(Side note: Manually cleaning up that copy-paste due to microsoft/terminal#1073 was _fun_.)

### CODE REVIEW

**Comment by dgw** [comment]
Closing in favor of #1689. Besides the fact that losing `#` comments in config files would suck, this solution also just doesn't work on Python 2.7: The `comment_prefixes` argument to `RawConfigParser` is not available until Python 3.2.
