### PR TITLE
remind: fix import streamlining gone haywire

### PR DESCRIPTION
**Pull request by dgw**
"Unexpected AttributeError: 'str' object has no attribute 'utc'" begone.

Fixes a bug I introduced in #2468 by not being careful enough with my imports. Code review or not, I should've caught it. (And I was reminded to finish/open this PR by `mypy --check-untyped-defs` flagging these errors, so that's all the more reason to work toward #2461 in the longer term.)

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

### Notes
`mypy --check-untyped-defs` still reports errors in `sopel/modules/remind.py` after this patch, but they'll be fixed separately. @SnoopJ and I have been chipping away at that list over the weekend.

### CODE REVIEW

**Review by SnoopJ — APPROVED** [review]
Changes look fine to me, although this would also be a good opportunity to add a test that would have caught the bug

**Comment by dgw** [comment]
> this would also be a good opportunity to add a test that would have caught the bug

Went for the minimum-necessary-change approach because:

1. As discovered shortly after, `mypy --check-untyped-defs` (the new default behavior of `make mypy`, soon) flags this problem
2. More importantly, the not-so-long-term plan is to replace this built-in plugin with an external [sopel-remind](https://github.com/sopel-irc/sopel-remind) package that already exists and has much better test coverage
